"""ONNX for ARC task324: rare seeds draw plaid-aware diagonal rays.

Task rule: the input is a two-color plaid-like background, generated by
choosing one structural color for selected full rows or selected full columns
and the other structural color elsewhere.  A few rare singleton colors replace
background cells.  Recover the replaced background color for each rare seed,
collect every NW/SE or NE/SW diagonal that passes through any seed, and repaint
cells on those diagonals when their original color equals that seed's recovered
background color.  The original seed cells and all untouched cells are
preserved.

ONNX: counts identify rare seed colors versus the two structural colors.  The
two-color plaid is recovered by testing every ordered structural-color pair as
an OR(row-selected, column-selected) model.  Static diagonal incidence matrices
turn seed positions into a line mask, and pair selectors repaint one-hot cells
without connected-component logic.
"""

from __future__ import annotations

import json
import math
import sys
from collections import Counter
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import onnx
import onnxruntime as ort
from onnx import TensorProto, helper, numpy_helper

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from score_model import score_file  # noqa: E402

TASK_ID = "task324"
OUT_DIR = Path(__file__).resolve().parent
BEST_PATH = OUT_DIR / "task324.onnx"
DATA_PATH = ROOT / "data" / "task324.json"

C = 10
H = W = 30
N = H * W
RARE_LIMIT = 8.0
IN_NAME = "input"
OUT_NAME = "output"
SHAPE = [1, C, H, W]
OPSET = 10
IR_VERSION = 10

ORDERED_COLOR_PAIRS = [(fg, bg) for fg in range(C) for bg in range(C) if fg != bg]
COLOR_PAIRS = [(seed, bg) for seed in range(C) for bg in range(C)]
P = len(ORDERED_COLOR_PAIRS)
Q = len(COLOR_PAIRS)
D = 2 * H - 1


def _init(inits: list[onnx.TensorProto], arr: Any, name: str) -> str:
    inits.append(numpy_helper.from_array(np.asarray(arr), name=name))
    return name


def _f32(inits: list[onnx.TensorProto], arr: Any, name: str) -> str:
    return _init(inits, np.asarray(arr, dtype=np.float32), name)


def _i64(inits: list[onnx.TensorProto], arr: Any, name: str) -> str:
    return _init(inits, np.asarray(arr, dtype=np.int64), name)


def _make_model(nodes: list[onnx.NodeProto], inits: list[onnx.TensorProto], name: str) -> onnx.ModelProto:
    x_info = helper.make_tensor_value_info(IN_NAME, TensorProto.FLOAT, SHAPE)
    y_info = helper.make_tensor_value_info(OUT_NAME, TensorProto.FLOAT, SHAPE)
    graph = helper.make_graph(nodes, name, [x_info], [y_info], initializer=inits)
    model = helper.make_model(
        graph,
        producer_name="",
        ir_version=IR_VERSION,
        opset_imports=[helper.make_opsetid("", OPSET)],
    )
    model.doc_string = ""
    onnx.checker.check_model(model)
    return model


def _grid_to_onehot(grid: Iterable[Iterable[int]]) -> np.ndarray:
    out = np.zeros(SHAPE, dtype=np.float32)
    for r, row in enumerate(grid):
        for c, color in enumerate(row):
            out[0, int(color), r, c] = 1.0
    return out


def _onehot_to_grid(onehot: np.ndarray) -> np.ndarray:
    return onehot.reshape(C, H, W).argmax(axis=0).astype(np.int64)


def _infer_plaid(grid: np.ndarray, rare_limit: int = int(RARE_LIMIT)) -> np.ndarray:
    """Recover the two-color OR(row, column) background pattern."""
    grid = np.asarray(grid, dtype=np.int64)
    counts = np.bincount(grid.ravel(), minlength=C)
    structural = sorted((c for c in range(C) if counts[c] >= rare_limit), key=lambda c: counts[c], reverse=True)[:2]
    if len(structural) != 2:
        raise ValueError(f"expected two structural colors, got {structural}")

    best: tuple[int, np.ndarray] | None = None
    for fg in structural:
        bg = structural[0] if structural[1] == fg else structural[1]
        known = np.isin(grid, structural)
        selected_rows = []
        for r in range(grid.shape[0]):
            values = grid[r][known[r]]
            selected_rows.append(bool(values.size and np.sum(values == bg) == 0))
        row_mask = np.asarray(selected_rows, dtype=bool)

        selected_cols = []
        for c in range(grid.shape[1]):
            values = grid[:, c][known[:, c] & ~row_mask]
            selected_cols.append(bool(values.size and np.any(values == fg)))
        col_mask = np.asarray(selected_cols, dtype=bool)

        pred = np.where(row_mask[:, None] | col_mask[None, :], fg, bg).astype(np.int64)
        errors = int(np.sum((pred != grid) & known))
        if best is None or errors < best[0]:
            best = (errors, pred)

    assert best is not None
    if best[0] != 0:
        raise ValueError(f"could not infer exact plaid, {best[0]} mismatches")
    return best[1]


def solve(grid: np.ndarray | list[list[int]]) -> np.ndarray:
    """Reference solver matching train, test, and arc-gen examples."""
    src = np.asarray(grid, dtype=np.int64)
    out = src.copy()
    counts = np.bincount(src.ravel(), minlength=C)
    plaid = _infer_plaid(src)

    seeds: list[tuple[int, int, int, int]] = []
    lines: set[tuple[str, int]] = set()
    for r in range(src.shape[0]):
        for c in range(src.shape[1]):
            color = int(src[r, c])
            if 0 < counts[color] < RARE_LIMIT:
                bg = int(plaid[r, c])
                seeds.append((r, c, color, bg))
                lines.add(("d", r - c))
                lines.add(("a", r + c))

    for r, c, seed_color, bg in seeds:
        for rr in range(src.shape[0]):
            for cc in range(src.shape[1]):
                if src[rr, cc] == bg and (("d", rr - cc) in lines or ("a", rr + cc) in lines):
                    out[rr, cc] = seed_color
        out[r, c] = seed_color
    return out


def _train_diagnostics() -> None:
    with DATA_PATH.open(encoding="utf-8") as fh:
        data = json.load(fh)

    print("train diagnostics")
    print("-----------------")
    for idx, ex in enumerate(data["train"]):
        src = np.asarray(ex["input"], dtype=np.int64)
        expected = np.asarray(ex["output"], dtype=np.int64)
        plaid = _infer_plaid(src)
        counts = np.bincount(src.ravel(), minlength=C)
        seeds = []
        lines = set()
        for r in range(src.shape[0]):
            for c in range(src.shape[1]):
                color = int(src[r, c])
                if 0 < counts[color] < RARE_LIMIT:
                    seeds.append((r, c, color, int(plaid[r, c])))
                    lines.add(("d", r - c))
                    lines.add(("a", r + c))

        print(f"train[{idx}] shape={src.shape} structural={Counter(src.ravel()).most_common(2)}")
        print(f"  shared lines: diag={sorted(v for k, v in lines if k == 'd')} anti={sorted(v for k, v in lines if k == 'a')}")
        for r, c, color, bg in seeds:
            painted = [
                (int(rr), int(cc))
                for rr, cc in np.argwhere((expected == color) & (src == bg))
                if ("d", int(rr - cc)) in lines or ("a", int(rr + cc)) in lines
            ]
            by_dir = {
                "NW": sum(rr < r and cc < c for rr, cc in painted),
                "NE": sum(rr < r and cc > c for rr, cc in painted),
                "SW": sum(rr > r and cc < c for rr, cc in painted),
                "SE": sum(rr > r and cc > c for rr, cc in painted),
            }
            print(
                f"  seed color={color} at=({r},{c}) region={bg} "
                f"painted={len(painted)} lengths={by_dir} coords={painted}"
            )


def _selector(rows: int, cols: int, items: list[tuple[int, int]], which: int) -> np.ndarray:
    arr = np.zeros((rows, cols), dtype=np.float32)
    for idx, pair in enumerate(items):
        arr[pair[which], idx] = 1.0
    return arr


def _pair_to_color(items: list[tuple[int, int]], which: int) -> np.ndarray:
    arr = np.zeros((len(items), C), dtype=np.float32)
    for idx, pair in enumerate(items):
        arr[idx, pair[which]] = 1.0
    return arr


def _diag_matrices() -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    cell_to_diag = np.zeros((N, D), dtype=np.float32)
    cell_to_anti = np.zeros((N, D), dtype=np.float32)
    for r in range(H):
        for c in range(W):
            flat = r * W + c
            cell_to_diag[flat, r - c + W - 1] = 1.0
            cell_to_anti[flat, r + c] = 1.0
    return cell_to_diag, cell_to_diag.T, cell_to_anti, cell_to_anti.T


def build_onnx_model() -> onnx.ModelProto:
    nodes: list[onnx.NodeProto] = []
    inits: list[onnx.TensorProto] = []

    half = _f32(inits, 0.5, "half")
    rare_limit = _f32(inits, RARE_LIMIT - 0.5, "rare_limit")
    one = _f32(inits, 1.0, "one")

    shape_1_10_900 = _i64(inits, [1, C, N], "shape_1_10_900")
    shape_1_p_900 = _i64(inits, [1, P, N], "shape_1_p_900")
    shape_1_p_hw = _i64(inits, [1, P, H, W], "shape_1_p_hw")
    shape_1_q_900 = _i64(inits, [1, Q, N], "shape_1_q_900")
    shape_1_q_hw = _i64(inits, [1, Q, H, W], "shape_1_q_hw")
    shape_1_q_1 = _i64(inits, [1, Q, 1], "shape_1_q_1")
    shape_1_900 = _i64(inits, [1, N], "shape_1_900")
    shape_1_1_hw = _i64(inits, [1, 1, H, W], "shape_1_1_hw")
    shape_1_10_hw = _i64(inits, [1, C, H, W], "shape_1_10_hw")
    shape_1_p_1_1 = _i64(inits, [1, P, 1, 1], "shape_1_p_1_1")
    shape_1_q_1_1 = _i64(inits, [1, Q, 1, 1], "shape_1_q_1_1")
    shape_1_10_1_1 = _i64(inits, [1, C, 1, 1], "shape_1_10_1_1")

    pair_fg = _f32(inits, _selector(C, P, ORDERED_COLOR_PAIRS, 0), "pair_fg")
    pair_bg = _f32(inits, _selector(C, P, ORDERED_COLOR_PAIRS, 1), "pair_bg")
    pair_fg_color = _f32(inits, _pair_to_color(ORDERED_COLOR_PAIRS, 0), "pair_fg_color")
    pair_bg_color = _f32(inits, _pair_to_color(ORDERED_COLOR_PAIRS, 1), "pair_bg_color")
    color_pair_seed = _f32(inits, _selector(C, Q, COLOR_PAIRS, 0), "color_pair_seed")
    color_pair_bg = _f32(inits, _selector(C, Q, COLOR_PAIRS, 1), "color_pair_bg")
    color_pair_seed_out = _f32(inits, _pair_to_color(COLOR_PAIRS, 0), "color_pair_seed_out")
    cell_to_diag, diag_to_cell, cell_to_anti, anti_to_cell = _diag_matrices()
    diag_in = _f32(inits, cell_to_diag, "diag_in")
    diag_out = _f32(inits, diag_to_cell, "diag_out")
    anti_in = _f32(inits, cell_to_anti, "anti_in")
    anti_out = _f32(inits, anti_to_cell, "anti_out")

    nodes.extend(
        [
            helper.make_node("Greater", [IN_NAME, half], ["x_bool"]),
            helper.make_node("ReduceSum", [IN_NAME], ["counts"], axes=[2, 3], keepdims=1),
            helper.make_node("Greater", ["counts", half], ["present_color"]),
            helper.make_node("Less", ["counts", rare_limit], ["rare_lt"]),
            helper.make_node("And", ["present_color", "rare_lt"], ["rare_color"]),
            helper.make_node("Not", ["rare_lt"], ["struct_color"]),
            helper.make_node("And", ["x_bool", "rare_color"], ["seed_bool"]),
            helper.make_node("Cast", ["seed_bool"], ["seed_f"], to=TensorProto.FLOAT),
            helper.make_node("ReduceSum", ["seed_f"], ["seed_any_sum"], axes=[1], keepdims=1),
            helper.make_node("Greater", ["seed_any_sum", half], ["seed_any_bool"]),
            helper.make_node("Cast", ["seed_any_bool"], ["seed_any_f"], to=TensorProto.FLOAT),
            helper.make_node("Reshape", ["seed_any_f", shape_1_900], ["seed_any_flat"]),
            helper.make_node("MatMul", ["seed_any_flat", diag_in], ["diag_scores"]),
            helper.make_node("Greater", ["diag_scores", half], ["diag_present_b"]),
            helper.make_node("Cast", ["diag_present_b"], ["diag_present"], to=TensorProto.FLOAT),
            helper.make_node("MatMul", ["diag_present", diag_out], ["diag_mask_sum"]),
            helper.make_node("MatMul", ["seed_any_flat", anti_in], ["anti_scores"]),
            helper.make_node("Greater", ["anti_scores", half], ["anti_present_b"]),
            helper.make_node("Cast", ["anti_present_b"], ["anti_present"], to=TensorProto.FLOAT),
            helper.make_node("MatMul", ["anti_present", anti_out], ["anti_mask_sum"]),
            helper.make_node("Add", ["diag_mask_sum", "anti_mask_sum"], ["line_mask_sum"]),
            helper.make_node("Greater", ["line_mask_sum", half], ["line_mask_flat_b"]),
            helper.make_node("Cast", ["line_mask_flat_b"], ["line_mask_flat"], to=TensorProto.FLOAT),
            helper.make_node("Reshape", ["line_mask_flat", shape_1_1_hw], ["line_mask"]),
        ]
    )

    # Ordered foreground/background plaid candidates.
    nodes.extend(
        [
            helper.make_node("Reshape", [IN_NAME, shape_1_10_900], ["x_10_flat"]),
            helper.make_node("Transpose", ["x_10_flat"], ["x_flat_10"], perm=[0, 2, 1]),
            helper.make_node("MatMul", ["x_flat_10", pair_fg], ["x_pair_fg_nhw"]),
            helper.make_node("MatMul", ["x_flat_10", pair_bg], ["x_pair_bg_nhw"]),
            helper.make_node("Transpose", ["x_pair_fg_nhw"], ["x_pair_fg_flat"], perm=[0, 2, 1]),
            helper.make_node("Transpose", ["x_pair_bg_nhw"], ["x_pair_bg_flat"], perm=[0, 2, 1]),
            helper.make_node("Reshape", ["x_pair_fg_flat", shape_1_p_hw], ["x_pair_fg"]),
            helper.make_node("Reshape", ["x_pair_bg_flat", shape_1_p_hw], ["x_pair_bg"]),
            helper.make_node("Greater", ["x_pair_fg", half], ["x_pair_fg_b"]),
            helper.make_node("Greater", ["x_pair_bg", half], ["x_pair_bg_b"]),
            helper.make_node("Or", ["x_pair_fg_b", "x_pair_bg_b"], ["known_pair"]),
            helper.make_node("ReduceSum", ["x_pair_bg"], ["row_bg_sum"], axes=[3], keepdims=1),
            helper.make_node("Less", ["row_bg_sum", half], ["row_selected"]),
            helper.make_node("Not", ["row_selected"], ["non_row_selected_b"]),
            helper.make_node("Cast", ["non_row_selected_b"], ["non_row_selected"], to=TensorProto.FLOAT),
            helper.make_node("Mul", ["x_pair_fg", "non_row_selected"], ["fg_non_selected_rows"]),
            helper.make_node("ReduceSum", ["fg_non_selected_rows"], ["col_fg_sum"], axes=[2], keepdims=1),
            helper.make_node("Greater", ["col_fg_sum", half], ["col_selected"]),
            helper.make_node("Or", ["row_selected", "col_selected"], ["pat_fg_b"]),
            helper.make_node("Not", ["x_pair_fg_b"], ["not_pair_fg"]),
            helper.make_node("Not", ["x_pair_bg_b"], ["not_pair_bg"]),
            helper.make_node("And", ["pat_fg_b", "not_pair_fg"], ["mismatch_fg0"]),
            helper.make_node("Not", ["pat_fg_b"], ["pat_bg_b"]),
            helper.make_node("And", ["pat_bg_b", "not_pair_bg"], ["mismatch_bg0"]),
            helper.make_node("Or", ["mismatch_fg0", "mismatch_bg0"], ["mismatch0"]),
            helper.make_node("And", ["mismatch0", "known_pair"], ["mismatch"]),
            helper.make_node("Cast", ["mismatch"], ["mismatch_f"], to=TensorProto.FLOAT),
            helper.make_node("ReduceSum", ["mismatch_f"], ["pair_errors"], axes=[2, 3], keepdims=0),
            helper.make_node("Reshape", ["struct_color", shape_1_10_1_1], ["struct_10"]),
            helper.make_node("Reshape", ["struct_10", _i64(inits, [1, C], "shape_1_10")], ["struct_flat"]),
            helper.make_node("Cast", ["struct_flat"], ["struct_flat_f"], to=TensorProto.FLOAT),
            helper.make_node("MatMul", ["struct_flat_f", pair_fg], ["pair_fg_struct_s"]),
            helper.make_node("MatMul", ["struct_flat_f", pair_bg], ["pair_bg_struct_s"]),
            helper.make_node("Greater", ["pair_fg_struct_s", half], ["pair_fg_struct"]),
            helper.make_node("Greater", ["pair_bg_struct_s", half], ["pair_bg_struct"]),
            helper.make_node("And", ["pair_fg_struct", "pair_bg_struct"], ["pair_struct"]),
            helper.make_node("Less", ["pair_errors", half], ["pair_zero_error"]),
            helper.make_node("And", ["pair_struct", "pair_zero_error"], ["model_pair_b"]),
            helper.make_node("Cast", ["model_pair_b"], ["model_pair"], to=TensorProto.FLOAT),
            helper.make_node("Reshape", ["model_pair", shape_1_p_1_1], ["model_pair_hw"]),
            helper.make_node("Cast", ["pat_fg_b"], ["pat_fg"], to=TensorProto.FLOAT),
            helper.make_node("Sub", [one, "pat_fg"], ["pat_bg"]),
            helper.make_node("Mul", ["pat_fg", "model_pair_hw"], ["chosen_fg_part"]),
            helper.make_node("Mul", ["pat_bg", "model_pair_hw"], ["chosen_bg_part"]),
            helper.make_node("Reshape", ["chosen_fg_part", shape_1_p_900], ["chosen_fg_flat"]),
            helper.make_node("Reshape", ["chosen_bg_part", shape_1_p_900], ["chosen_bg_flat"]),
            helper.make_node("Transpose", ["chosen_fg_flat"], ["chosen_fg_nhp"], perm=[0, 2, 1]),
            helper.make_node("Transpose", ["chosen_bg_flat"], ["chosen_bg_nhp"], perm=[0, 2, 1]),
            helper.make_node("MatMul", ["chosen_fg_nhp", pair_fg_color], ["pat_fg_color_nh10"]),
            helper.make_node("MatMul", ["chosen_bg_nhp", pair_bg_color], ["pat_bg_color_nh10"]),
            helper.make_node("Add", ["pat_fg_color_nh10", "pat_bg_color_nh10"], ["pat_color_nh10"]),
            helper.make_node("Transpose", ["pat_color_nh10"], ["pat_color_10_flat"], perm=[0, 2, 1]),
            helper.make_node("Reshape", ["pat_color_10_flat", shape_1_10_hw], ["pat_color"]),
        ]
    )

    # Which (seed color, recovered background color) pairs exist?
    nodes.extend(
        [
            helper.make_node("MatMul", ["x_flat_10", color_pair_seed], ["x_pair_seed_nh"]),
            helper.make_node("Transpose", ["pat_color_10_flat"], ["pat_color_nh10_b"], perm=[0, 2, 1]),
            helper.make_node("MatMul", ["pat_color_nh10_b", color_pair_bg], ["pat_pair_bg_nh"]),
            helper.make_node("Transpose", ["x_pair_seed_nh"], ["x_pair_seed_flat"], perm=[0, 2, 1]),
            helper.make_node("Transpose", ["pat_pair_bg_nh"], ["pat_pair_bg_flat"], perm=[0, 2, 1]),
            helper.make_node("Reshape", ["x_pair_seed_flat", shape_1_q_900], ["x_pair_seed"]),
            helper.make_node("Reshape", ["pat_pair_bg_flat", shape_1_q_900], ["pat_pair_bg"]),
            helper.make_node("Reshape", ["rare_color", shape_1_10_1_1], ["rare_color_10"]),
            helper.make_node("Reshape", ["rare_color_10", _i64(inits, [1, C], "shape_1_10_b")], ["rare_flat"]),
            helper.make_node("Cast", ["rare_flat"], ["rare_flat_f"], to=TensorProto.FLOAT),
            helper.make_node("MatMul", ["rare_flat_f", color_pair_seed], ["rare_pair_seed_s"]),
            helper.make_node("Greater", ["rare_pair_seed_s", half], ["rare_pair_seed"]),
            helper.make_node("Cast", ["rare_pair_seed"], ["rare_pair_seed_f"], to=TensorProto.FLOAT),
            helper.make_node("Mul", ["x_pair_seed", "pat_pair_bg"], ["seed_bg_cells0"]),
            helper.make_node("Reshape", ["rare_pair_seed_f", shape_1_q_1], ["rare_pair_seed_flat"]),
            helper.make_node("Mul", ["seed_bg_cells0", "rare_pair_seed_flat"], ["seed_bg_cells"]),
            helper.make_node("ReduceSum", ["seed_bg_cells"], ["seed_bg_pair_scores"], axes=[2], keepdims=0),
            helper.make_node("Greater", ["seed_bg_pair_scores", half], ["seed_bg_pair_b"]),
            helper.make_node("Cast", ["seed_bg_pair_b"], ["seed_bg_pair"], to=TensorProto.FLOAT),
            helper.make_node("Reshape", ["seed_bg_pair", shape_1_q_1_1], ["seed_bg_pair_hw"]),
        ]
    )

    # Paint original background cells that are on any seed diagonal.
    nodes.extend(
        [
            helper.make_node("MatMul", ["x_flat_10", color_pair_bg], ["x_pair_target_bg_nh"]),
            helper.make_node("Transpose", ["x_pair_target_bg_nh"], ["x_pair_target_bg_flat"], perm=[0, 2, 1]),
            helper.make_node("Reshape", ["x_pair_target_bg_flat", shape_1_q_hw], ["x_pair_target_bg"]),
            helper.make_node("Mul", ["x_pair_target_bg", "seed_bg_pair_hw"], ["paint_pair0"]),
            helper.make_node("Mul", ["paint_pair0", "line_mask"], ["paint_pair"]),
            helper.make_node("Reshape", ["paint_pair", shape_1_q_900], ["paint_pair_flat"]),
            helper.make_node("Transpose", ["paint_pair_flat"], ["paint_pair_nhq"], perm=[0, 2, 1]),
            helper.make_node("MatMul", ["paint_pair_nhq", color_pair_seed_out], ["paint_nh10"]),
            helper.make_node("Transpose", ["paint_nh10"], ["paint_10_flat"], perm=[0, 2, 1]),
            helper.make_node("Reshape", ["paint_10_flat", shape_1_10_hw], ["paint_sum"]),
            helper.make_node("Greater", ["paint_sum", half], ["paint_b"]),
            helper.make_node("Cast", ["paint_b"], ["paint_f"], to=TensorProto.FLOAT),
            helper.make_node("ReduceSum", ["paint_f"], ["paint_any_sum"], axes=[1], keepdims=1),
            helper.make_node("Greater", ["paint_any_sum", half], ["paint_any_b"]),
            helper.make_node("Where", ["paint_any_b", "paint_f", IN_NAME], [OUT_NAME]),
        ]
    )

    return _make_model(nodes, inits, "task324_plaid_diagonal_rays")


def _run_onnx(model: onnx.ModelProto, grid: list[list[int]]) -> np.ndarray:
    session = ort.InferenceSession(model.SerializeToString(), providers=["CPUExecutionProvider"])
    return session.run([OUT_NAME], {IN_NAME: _grid_to_onehot(grid)})[0]


def validate_json(model: onnx.ModelProto) -> int:
    with DATA_PATH.open(encoding="utf-8") as fh:
        data = json.load(fh)

    bad = 0
    for split in ("train", "test", "arc-gen"):
        for idx, ex in enumerate(data[split]):
            expected = np.asarray(ex["output"], dtype=np.int64)
            ref = solve(ex["input"])
            if not np.array_equal(ref, expected):
                raise AssertionError(f"reference mismatch on {split}[{idx}]")

            pred_oh = _run_onnx(model, ex["input"])
            pred = _onehot_to_grid(pred_oh)[: expected.shape[0], : expected.shape[1]]
            active = pred_oh[0, :, : expected.shape[0], : expected.shape[1]] > 0
            pad_active = np.any(pred_oh[0, :, expected.shape[0] :, :] > 0) or np.any(
                pred_oh[0, :, :, expected.shape[1] :] > 0
            )
            if not np.array_equal(pred, expected) or not np.all(active.sum(axis=0) == 1) or pad_active:
                print(f"ONNX mismatch {split}[{idx}] cells={int(np.sum(pred != expected))} pad_active={pad_active}")
                bad += 1
                if bad <= 3:
                    print("expected")
                    print(expected)
                    print("pred")
                    print(pred)
    return bad


def model_stats(model: onnx.ModelProto, path: Path | None = None) -> dict[str, int]:
    return {
        "bytes": path.stat().st_size if path and path.is_file() else len(model.SerializeToString()),
        "nodes": len(model.graph.node),
        "inits": len(model.graph.initializer),
        "params": int(sum(np.prod(init.dims) for init in model.graph.initializer)),
        "opset": model.opset_import[0].version,
        "ir": model.ir_version,
    }


def save_model(path: Path = BEST_PATH) -> onnx.ModelProto:
    model = build_onnx_model()
    path.parent.mkdir(parents=True, exist_ok=True)
    onnx.save(model, str(path))
    return model


def main() -> None:
    _train_diagnostics()
    model = save_model()
    stats = model_stats(model, BEST_PATH)
    print()
    print(f"saved {BEST_PATH}")
    print(f"stats: {stats}")
    bad = validate_json(model)
    print(f"json/onnx validation: {'PASS' if bad == 0 else f'FAIL bad={bad}'}")
    if bad:
        raise SystemExit(1)

    result = score_file(BEST_PATH)
    print(
        "score_model: "
        f"valid={result['valid']} memory={result['memory']} params={result['params']} "
        f"cost={result['cost']} score={float(result['score']):.6f}"
    )
    print(f"hypothesis kept: plaid-recovered seed regions + all seed diagonals ({25 - math.log(max(1, result['cost'])):.6f} raw)")


if __name__ == "__main__":
    main()
